liteflow:
  rule-source-ext-data-map:
    url: jdbc:mysql://localhost:3306/jeecg-boot
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeecg-boot
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ''
